### ISSUE TITLE
关于含有下拉刷新控件布局不显示问题

### ISSUE THREAD

**Issue by Roben1016** [jiang-banzhi/StatusMamager#1]
你好, 我的项目中用到了SmartRefreshLayout和RecycleView进行下拉刷新, 发现空布局, 错误布局和原布局都不展示, 只有在SmartRefreshLayout下再嵌套一层布局才可以,不知道有没有解决办法. 之前也找过好几个类似的库, 貌似都存在这个问题.

**Comment by getglory** [comment]
> 你好, 我的项目中用到了SmartRefreshLayout和RecycleView进行下拉刷新, 发现空布局, 错误布局和原布局都不展示, 只有在SmartRefreshLayout下再嵌套一层布局才可以,不知道有没有解决办法. 之前也找过好几个类似的库, 貌似都存在这个问题.

RecyclerView没有数据，可用直接添加一个空布局的item来展示，通过viewtype来判断展示的item类型。
我是用BaseRecyclerViewAdapterHelper这个Adapter，可用直接设置空布局。这个控件是设置根布局的空布局之类用
